#include <stdio.h>

int main() {

  printf("EEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEEE\nEEEE\nEEEE\nEEEE\nEEEE\nEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEE\nEEEE\nEEEE\nEEEE\nEEEE\nEEEEEEEEEEEEEEEEEEE\nEEEEEEEEEEEEEEEEEEE\n");
  printf("\n");
  printf("FFFFFFFFFFFFFFFFFFF\nFFFFFFFFFFFFFFFFFFF\nFFFF\nFFFF\nFFFF\nFFFF\nFFFFFFFFFFFFFFFFFFF\nFFFFFFFFFFFFFFFFFFF\nFFFF\nFFFF\nFFFF\nFFFF\nFFFF\nFFFF\n");

  return 0;
}